### ISSUE TITLE
I have an issue with VatTaxableCHF for VAT code V0-N

### ISSUE THREAD

**Issue by DiegoFi** [BananaAccounting/Switzerland#2]
[Transactions.xlsx](https://github.com/BananaAccounting/Switzerland/files/2880761/Transactions.xlsx)
based on these entries it should be 10'999.95 but I get 11'244.57
[2018.YE Dichiarazione IVA CHF.docx](https://github.com/BananaAccounting/Switzerland/files/2880770/2018.YE.Dichiarazione.IVA.CHF.docx)

**Comment by claudia2** [comment]
Please contact our support for questions email: support@banana.ch
